export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as News} from './news/News'
export {default as Product} from './product/Product'
export {default as About} from './about/About'